### ISSUE TITLE
responsive font sizes blog page for mobile

### ISSUE THREAD

**Issue by edrisranjbar** [abdolmajidbn/JetCode-Theme#10]
we need to implement proper font sizes for titles, post titles and etc.

**Comment by edrisranjbar** [comment]
Done

**Comment by WhenOkabeMetSubaru** [comment]
I want to contribute it would be really helpful if you can guide me on this

**Comment by edrisranjbar** [comment]
Thanks for your interest. by the time your responded we already have fixed the issue; but for other issues fill free to ask any question you have. we appreciate any help in this free project.
